spring.application.name=suryaapi
# for enable exception
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.error.whitelabel.enabled=false




# Mysql  DATABASE surya_api;


spring.datasource.url=jdbc:mysql://localhost:3306/surya_api?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Surya@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# mail otp details 
#kjir bhto dxwk dbyk
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=surya.angularjs@gmail.com
spring.mail.password=kjirbhtodxwkdbyk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
